// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restaurant-service/restaurant.proto

package restaurant_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Restaurant struct {
	ResId                uint64            `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               float64           `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Cuisines             []string          `protobuf:"bytes,4,rep,name=cuisines,proto3" json:"cuisines,omitempty"`
	CostForTwo           float64           `protobuf:"fixed64,5,opt,name=cost_for_two,json=costForTwo,proto3" json:"cost_for_two,omitempty"`
	OpeningTime          string            `protobuf:"bytes,6,opt,name=opening_time,json=openingTime,proto3" json:"opening_time,omitempty"`
	ClosingTime          string            `protobuf:"bytes,7,opt,name=closing_time,json=closingTime,proto3" json:"closing_time,omitempty"`
	Coordinates          *Restaurant_Point `protobuf:"bytes,8,opt,name=coordinates,proto3" json:"coordinates,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa7dcbccfe3879, []int{0}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetResId() uint64 {
	if m != nil {
		return m.ResId
	}
	return 0
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Restaurant) GetCuisines() []string {
	if m != nil {
		return m.Cuisines
	}
	return nil
}

func (m *Restaurant) GetCostForTwo() float64 {
	if m != nil {
		return m.CostForTwo
	}
	return 0
}

func (m *Restaurant) GetOpeningTime() string {
	if m != nil {
		return m.OpeningTime
	}
	return ""
}

func (m *Restaurant) GetClosingTime() string {
	if m != nil {
		return m.ClosingTime
	}
	return ""
}

func (m *Restaurant) GetCoordinates() *Restaurant_Point {
	if m != nil {
		return m.Coordinates
	}
	return nil
}

type Restaurant_Point struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant_Point) Reset()         { *m = Restaurant_Point{} }
func (m *Restaurant_Point) String() string { return proto.CompactTextString(m) }
func (*Restaurant_Point) ProtoMessage()    {}
func (*Restaurant_Point) Descriptor() ([]byte, []int) {
	return fileDescriptor_4caa7dcbccfe3879, []int{0, 0}
}

func (m *Restaurant_Point) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant_Point.Unmarshal(m, b)
}
func (m *Restaurant_Point) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant_Point.Marshal(b, m, deterministic)
}
func (m *Restaurant_Point) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant_Point.Merge(m, src)
}
func (m *Restaurant_Point) XXX_Size() int {
	return xxx_messageInfo_Restaurant_Point.Size(m)
}
func (m *Restaurant_Point) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant_Point.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant_Point proto.InternalMessageInfo

func (m *Restaurant_Point) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Restaurant_Point) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

func init() {
	proto.RegisterType((*Restaurant)(nil), "restaurant_service.Restaurant")
	proto.RegisterType((*Restaurant_Point)(nil), "restaurant_service.Restaurant.Point")
}

func init() {
	proto.RegisterFile("restaurant-service/restaurant.proto", fileDescriptor_4caa7dcbccfe3879)
}

var fileDescriptor_4caa7dcbccfe3879 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x5f, 0x8b, 0xda, 0x40,
	0x14, 0xc5, 0x1d, 0xff, 0xa4, 0x7a, 0xb5, 0xc5, 0x0e, 0x54, 0x42, 0x0a, 0x25, 0xb5, 0x7d, 0xc8,
	0x8b, 0xb1, 0xd8, 0x4f, 0x20, 0x54, 0x8b, 0xa5, 0x94, 0x32, 0xeb, 0x7b, 0x88, 0xc9, 0x35, 0x0c,
	0x24, 0x33, 0x32, 0x33, 0xae, 0xec, 0x37, 0x5c, 0xf6, 0x53, 0x2d, 0x99, 0x64, 0x8d, 0xb0, 0xec,
	0xee, 0x8b, 0x6f, 0x77, 0x0e, 0xbf, 0x73, 0x6e, 0x72, 0x2e, 0x7c, 0x53, 0xa8, 0x4d, 0x7c, 0x54,
	0xb1, 0x30, 0x33, 0x8d, 0xea, 0x96, 0x27, 0x38, 0x6f, 0xa4, 0xf0, 0xa0, 0xa4, 0x91, 0x94, 0x36,
	0x4a, 0x54, 0x43, 0xde, 0xe7, 0x4c, 0xca, 0x2c, 0xc7, 0xb9, 0x25, 0x76, 0xc7, 0xfd, 0x1c, 0x8b,
	0x83, 0xb9, 0xab, 0x0c, 0xd3, 0x87, 0x36, 0x00, 0x3b, 0x7b, 0xe8, 0x27, 0x70, 0x14, 0xea, 0x88,
	0xa7, 0x2e, 0xf1, 0x49, 0xd0, 0x65, 0x3d, 0x85, 0x7a, 0x93, 0x52, 0x0a, 0x5d, 0x11, 0x17, 0xe8,
	0xb6, 0x7d, 0x12, 0x0c, 0x98, 0x9d, 0xe9, 0x04, 0x1c, 0x15, 0x1b, 0x2e, 0x32, 0xb7, 0xe3, 0x93,
	0x80, 0xb0, 0xfa, 0x45, 0x3d, 0xe8, 0x27, 0x47, 0xae, 0xb9, 0x40, 0xed, 0x76, 0xfd, 0x4e, 0x30,
	0x60, 0xe7, 0x37, 0xf5, 0x61, 0x94, 0x48, 0x6d, 0xa2, 0xbd, 0x54, 0x91, 0x39, 0x49, 0xb7, 0x67,
	0x9d, 0x50, 0x6a, 0x6b, 0xa9, 0xb6, 0x27, 0x49, 0xbf, 0xc2, 0x48, 0x1e, 0x50, 0x70, 0x91, 0x45,
	0x86, 0x17, 0xe8, 0x3a, 0x76, 0xe3, 0xb0, 0xd6, 0xb6, 0xbc, 0xc0, 0x12, 0x49, 0x72, 0xa9, 0xcf,
	0xc8, 0xbb, 0x0a, 0xa9, 0x35, 0x8b, 0xac, 0x61, 0x98, 0x48, 0xa9, 0x52, 0x2e, 0x62, 0x83, 0xda,
	0xed, 0xfb, 0x24, 0x18, 0x2e, 0xbe, 0x87, 0xcf, 0xcb, 0x09, 0x9b, 0x7f, 0x0f, 0xff, 0x4b, 0x2e,
	0x0c, 0xbb, 0x34, 0x7a, 0x33, 0xe8, 0x59, 0x95, 0x8e, 0xa1, 0x93, 0xc7, 0xc6, 0x96, 0x42, 0x58,
	0x39, 0x96, 0x95, 0xe4, 0x52, 0x64, 0xb6, 0x12, 0xc2, 0xec, 0xbc, 0xb8, 0x6f, 0xc3, 0xc7, 0x26,
	0xf0, 0xa6, 0x5a, 0x41, 0x37, 0xf0, 0x7e, 0x99, 0xa6, 0x17, 0x25, 0x7f, 0x79, 0xfd, 0x43, 0xbc,
	0x49, 0x58, 0x5d, 0x2c, 0x7c, 0xba, 0x58, 0xb8, 0x2a, 0x2f, 0x36, 0x6d, 0xd1, 0x3f, 0xf0, 0x61,
	0x95, 0x72, 0x73, 0x95, 0xac, 0xbf, 0x30, 0xfe, 0x85, 0x39, 0x1a, 0xbc, 0x4a, 0xda, 0x3f, 0x18,
	0xff, 0x46, 0xb3, 0xcc, 0xf3, 0x8b, 0xb4, 0x17, 0x68, 0xef, 0x8d, 0x2d, 0xd3, 0xd6, 0x0f, 0xb2,
	0x73, 0xac, 0xe7, 0xe7, 0x63, 0x00, 0x00, 0x00, 0xff, 0xff, 0x6c, 0xf8, 0x27, 0x25, 0xf6, 0x02,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	AddRestaurant(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*empty.Empty, error)
	EditRestaurant(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*empty.Empty, error)
	DeleteRestaurant(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*empty.Empty, error)
	GetAllRestaurant(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RestaurantService_GetAllRestaurantClient, error)
}

type restaurantServiceClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantServiceClient(cc *grpc.ClientConn) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) AddRestaurant(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/AddRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) EditRestaurant(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/EditRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) DeleteRestaurant(ctx context.Context, in *Restaurant, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/DeleteRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetAllRestaurant(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (RestaurantService_GetAllRestaurantClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RestaurantService_serviceDesc.Streams[0], "/restaurant_service.RestaurantService/GetAllRestaurant", opts...)
	if err != nil {
		return nil, err
	}
	x := &restaurantServiceGetAllRestaurantClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RestaurantService_GetAllRestaurantClient interface {
	Recv() (*Restaurant, error)
	grpc.ClientStream
}

type restaurantServiceGetAllRestaurantClient struct {
	grpc.ClientStream
}

func (x *restaurantServiceGetAllRestaurantClient) Recv() (*Restaurant, error) {
	m := new(Restaurant)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
type RestaurantServiceServer interface {
	AddRestaurant(context.Context, *Restaurant) (*empty.Empty, error)
	EditRestaurant(context.Context, *Restaurant) (*empty.Empty, error)
	DeleteRestaurant(context.Context, *Restaurant) (*empty.Empty, error)
	GetAllRestaurant(*empty.Empty, RestaurantService_GetAllRestaurantServer) error
}

// UnimplementedRestaurantServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantServiceServer struct {
}

func (*UnimplementedRestaurantServiceServer) AddRestaurant(ctx context.Context, req *Restaurant) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) EditRestaurant(ctx context.Context, req *Restaurant) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) DeleteRestaurant(ctx context.Context, req *Restaurant) (*empty.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) GetAllRestaurant(req *empty.Empty, srv RestaurantService_GetAllRestaurantServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllRestaurant not implemented")
}

func RegisterRestaurantServiceServer(s *grpc.Server, srv RestaurantServiceServer) {
	s.RegisterService(&_RestaurantService_serviceDesc, srv)
}

func _RestaurantService_AddRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).AddRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/AddRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).AddRestaurant(ctx, req.(*Restaurant))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_EditRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).EditRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/EditRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).EditRestaurant(ctx, req.(*Restaurant))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_DeleteRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Restaurant)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).DeleteRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/DeleteRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).DeleteRestaurant(ctx, req.(*Restaurant))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetAllRestaurant_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(empty.Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestaurantServiceServer).GetAllRestaurant(m, &restaurantServiceGetAllRestaurantServer{stream})
}

type RestaurantService_GetAllRestaurantServer interface {
	Send(*Restaurant) error
	grpc.ServerStream
}

type restaurantServiceGetAllRestaurantServer struct {
	grpc.ServerStream
}

func (x *restaurantServiceGetAllRestaurantServer) Send(m *Restaurant) error {
	return x.ServerStream.SendMsg(m)
}

var _RestaurantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant_service.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRestaurant",
			Handler:    _RestaurantService_AddRestaurant_Handler,
		},
		{
			MethodName: "EditRestaurant",
			Handler:    _RestaurantService_EditRestaurant_Handler,
		},
		{
			MethodName: "DeleteRestaurant",
			Handler:    _RestaurantService_DeleteRestaurant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllRestaurant",
			Handler:       _RestaurantService_GetAllRestaurant_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "restaurant-service/restaurant.proto",
}
