// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/restaurant.proto

package restaurant_service

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status_StatusCode int32

const (
	Status_FAIL    Status_StatusCode = 0
	Status_SUCCESS Status_StatusCode = 1
)

var Status_StatusCode_name = map[int32]string{
	0: "FAIL",
	1: "SUCCESS",
}

var Status_StatusCode_value = map[string]int32{
	"FAIL":    0,
	"SUCCESS": 1,
}

func (x Status_StatusCode) String() string {
	return proto.EnumName(Status_StatusCode_name, int32(x))
}

func (Status_StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{1, 0}
}

type Restaurant struct {
	ResId                uint64               `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               float64              `protobuf:"fixed64,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Cuisines             []string             `protobuf:"bytes,4,rep,name=cuisines,proto3" json:"cuisines,omitempty"`
	CostForTwo           float64              `protobuf:"fixed64,5,opt,name=cost_for_two,json=costForTwo,proto3" json:"cost_for_two,omitempty"`
	OpeningTime          string               `protobuf:"bytes,6,opt,name=opening_time,json=openingTime,proto3" json:"opening_time,omitempty"`
	ClosingTime          string               `protobuf:"bytes,7,opt,name=closing_time,json=closingTime,proto3" json:"closing_time,omitempty"`
	Location             *Restaurant_Location `protobuf:"bytes,8,opt,name=location,proto3" json:"location,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Restaurant) Reset()         { *m = Restaurant{} }
func (m *Restaurant) String() string { return proto.CompactTextString(m) }
func (*Restaurant) ProtoMessage()    {}
func (*Restaurant) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{0}
}

func (m *Restaurant) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant.Unmarshal(m, b)
}
func (m *Restaurant) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant.Marshal(b, m, deterministic)
}
func (m *Restaurant) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant.Merge(m, src)
}
func (m *Restaurant) XXX_Size() int {
	return xxx_messageInfo_Restaurant.Size(m)
}
func (m *Restaurant) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant proto.InternalMessageInfo

func (m *Restaurant) GetResId() uint64 {
	if m != nil {
		return m.ResId
	}
	return 0
}

func (m *Restaurant) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Restaurant) GetRating() float64 {
	if m != nil {
		return m.Rating
	}
	return 0
}

func (m *Restaurant) GetCuisines() []string {
	if m != nil {
		return m.Cuisines
	}
	return nil
}

func (m *Restaurant) GetCostForTwo() float64 {
	if m != nil {
		return m.CostForTwo
	}
	return 0
}

func (m *Restaurant) GetOpeningTime() string {
	if m != nil {
		return m.OpeningTime
	}
	return ""
}

func (m *Restaurant) GetClosingTime() string {
	if m != nil {
		return m.ClosingTime
	}
	return ""
}

func (m *Restaurant) GetLocation() *Restaurant_Location {
	if m != nil {
		return m.Location
	}
	return nil
}

type Restaurant_Location struct {
	Lat                  float64  `protobuf:"fixed64,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Long                 float64  `protobuf:"fixed64,2,opt,name=long,proto3" json:"long,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Restaurant_Location) Reset()         { *m = Restaurant_Location{} }
func (m *Restaurant_Location) String() string { return proto.CompactTextString(m) }
func (*Restaurant_Location) ProtoMessage()    {}
func (*Restaurant_Location) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{0, 0}
}

func (m *Restaurant_Location) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restaurant_Location.Unmarshal(m, b)
}
func (m *Restaurant_Location) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restaurant_Location.Marshal(b, m, deterministic)
}
func (m *Restaurant_Location) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restaurant_Location.Merge(m, src)
}
func (m *Restaurant_Location) XXX_Size() int {
	return xxx_messageInfo_Restaurant_Location.Size(m)
}
func (m *Restaurant_Location) XXX_DiscardUnknown() {
	xxx_messageInfo_Restaurant_Location.DiscardUnknown(m)
}

var xxx_messageInfo_Restaurant_Location proto.InternalMessageInfo

func (m *Restaurant_Location) GetLat() float64 {
	if m != nil {
		return m.Lat
	}
	return 0
}

func (m *Restaurant_Location) GetLong() float64 {
	if m != nil {
		return m.Long
	}
	return 0
}

type Status struct {
	Code                 Status_StatusCode `protobuf:"varint,1,opt,name=code,proto3,enum=restaurant_service.Status_StatusCode" json:"code,omitempty"`
	Message              string            `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{1}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() Status_StatusCode {
	if m != nil {
		return m.Code
	}
	return Status_FAIL
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AddRestaurantRequest struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AddRestaurantRequest) Reset()         { *m = AddRestaurantRequest{} }
func (m *AddRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantRequest) ProtoMessage()    {}
func (*AddRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{2}
}

func (m *AddRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantRequest.Unmarshal(m, b)
}
func (m *AddRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *AddRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantRequest.Merge(m, src)
}
func (m *AddRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantRequest.Size(m)
}
func (m *AddRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantRequest proto.InternalMessageInfo

func (m *AddRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type AddRestaurantResponse struct {
	ResId                uint64   `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddRestaurantResponse) Reset()         { *m = AddRestaurantResponse{} }
func (m *AddRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*AddRestaurantResponse) ProtoMessage()    {}
func (*AddRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{3}
}

func (m *AddRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddRestaurantResponse.Unmarshal(m, b)
}
func (m *AddRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *AddRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddRestaurantResponse.Merge(m, src)
}
func (m *AddRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_AddRestaurantResponse.Size(m)
}
func (m *AddRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AddRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AddRestaurantResponse proto.InternalMessageInfo

func (m *AddRestaurantResponse) GetResId() uint64 {
	if m != nil {
		return m.ResId
	}
	return 0
}

func (m *AddRestaurantResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetRestaurantRequest struct {
	ResId                uint64   `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetRestaurantRequest) Reset()         { *m = GetRestaurantRequest{} }
func (m *GetRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*GetRestaurantRequest) ProtoMessage()    {}
func (*GetRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{4}
}

func (m *GetRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRestaurantRequest.Unmarshal(m, b)
}
func (m *GetRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *GetRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRestaurantRequest.Merge(m, src)
}
func (m *GetRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_GetRestaurantRequest.Size(m)
}
func (m *GetRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetRestaurantRequest proto.InternalMessageInfo

func (m *GetRestaurantRequest) GetResId() uint64 {
	if m != nil {
		return m.ResId
	}
	return 0
}

type GetRestaurantResponse struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	Status               *Status     `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetRestaurantResponse) Reset()         { *m = GetRestaurantResponse{} }
func (m *GetRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*GetRestaurantResponse) ProtoMessage()    {}
func (*GetRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{5}
}

func (m *GetRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetRestaurantResponse.Unmarshal(m, b)
}
func (m *GetRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *GetRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetRestaurantResponse.Merge(m, src)
}
func (m *GetRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_GetRestaurantResponse.Size(m)
}
func (m *GetRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetRestaurantResponse proto.InternalMessageInfo

func (m *GetRestaurantResponse) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

func (m *GetRestaurantResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type EditRestaurantRequest struct {
	Restaurant           *Restaurant `protobuf:"bytes,1,opt,name=restaurant,proto3" json:"restaurant,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *EditRestaurantRequest) Reset()         { *m = EditRestaurantRequest{} }
func (m *EditRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*EditRestaurantRequest) ProtoMessage()    {}
func (*EditRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{6}
}

func (m *EditRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRestaurantRequest.Unmarshal(m, b)
}
func (m *EditRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *EditRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRestaurantRequest.Merge(m, src)
}
func (m *EditRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_EditRestaurantRequest.Size(m)
}
func (m *EditRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EditRestaurantRequest proto.InternalMessageInfo

func (m *EditRestaurantRequest) GetRestaurant() *Restaurant {
	if m != nil {
		return m.Restaurant
	}
	return nil
}

type EditRestaurantResponse struct {
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EditRestaurantResponse) Reset()         { *m = EditRestaurantResponse{} }
func (m *EditRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*EditRestaurantResponse) ProtoMessage()    {}
func (*EditRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{7}
}

func (m *EditRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EditRestaurantResponse.Unmarshal(m, b)
}
func (m *EditRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EditRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *EditRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EditRestaurantResponse.Merge(m, src)
}
func (m *EditRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_EditRestaurantResponse.Size(m)
}
func (m *EditRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EditRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EditRestaurantResponse proto.InternalMessageInfo

func (m *EditRestaurantResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type DeleteRestaurantRequest struct {
	ResId                uint64   `protobuf:"varint,1,opt,name=res_id,json=resId,proto3" json:"res_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantRequest) Reset()         { *m = DeleteRestaurantRequest{} }
func (m *DeleteRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantRequest) ProtoMessage()    {}
func (*DeleteRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{8}
}

func (m *DeleteRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantRequest.Unmarshal(m, b)
}
func (m *DeleteRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantRequest.Merge(m, src)
}
func (m *DeleteRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantRequest.Size(m)
}
func (m *DeleteRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantRequest proto.InternalMessageInfo

func (m *DeleteRestaurantRequest) GetResId() uint64 {
	if m != nil {
		return m.ResId
	}
	return 0
}

type DeleteRestaurantResponse struct {
	Status               *Status  `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRestaurantResponse) Reset()         { *m = DeleteRestaurantResponse{} }
func (m *DeleteRestaurantResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRestaurantResponse) ProtoMessage()    {}
func (*DeleteRestaurantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{9}
}

func (m *DeleteRestaurantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRestaurantResponse.Unmarshal(m, b)
}
func (m *DeleteRestaurantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRestaurantResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRestaurantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRestaurantResponse.Merge(m, src)
}
func (m *DeleteRestaurantResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRestaurantResponse.Size(m)
}
func (m *DeleteRestaurantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRestaurantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRestaurantResponse proto.InternalMessageInfo

func (m *DeleteRestaurantResponse) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetAllRestaurantRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAllRestaurantRequest) Reset()         { *m = GetAllRestaurantRequest{} }
func (m *GetAllRestaurantRequest) String() string { return proto.CompactTextString(m) }
func (*GetAllRestaurantRequest) ProtoMessage()    {}
func (*GetAllRestaurantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2a748d3fbc2b9a53, []int{10}
}

func (m *GetAllRestaurantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAllRestaurantRequest.Unmarshal(m, b)
}
func (m *GetAllRestaurantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAllRestaurantRequest.Marshal(b, m, deterministic)
}
func (m *GetAllRestaurantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAllRestaurantRequest.Merge(m, src)
}
func (m *GetAllRestaurantRequest) XXX_Size() int {
	return xxx_messageInfo_GetAllRestaurantRequest.Size(m)
}
func (m *GetAllRestaurantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAllRestaurantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAllRestaurantRequest proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("restaurant_service.Status_StatusCode", Status_StatusCode_name, Status_StatusCode_value)
	proto.RegisterType((*Restaurant)(nil), "restaurant_service.Restaurant")
	proto.RegisterType((*Restaurant_Location)(nil), "restaurant_service.Restaurant.Location")
	proto.RegisterType((*Status)(nil), "restaurant_service.Status")
	proto.RegisterType((*AddRestaurantRequest)(nil), "restaurant_service.AddRestaurantRequest")
	proto.RegisterType((*AddRestaurantResponse)(nil), "restaurant_service.AddRestaurantResponse")
	proto.RegisterType((*GetRestaurantRequest)(nil), "restaurant_service.GetRestaurantRequest")
	proto.RegisterType((*GetRestaurantResponse)(nil), "restaurant_service.GetRestaurantResponse")
	proto.RegisterType((*EditRestaurantRequest)(nil), "restaurant_service.EditRestaurantRequest")
	proto.RegisterType((*EditRestaurantResponse)(nil), "restaurant_service.EditRestaurantResponse")
	proto.RegisterType((*DeleteRestaurantRequest)(nil), "restaurant_service.DeleteRestaurantRequest")
	proto.RegisterType((*DeleteRestaurantResponse)(nil), "restaurant_service.DeleteRestaurantResponse")
	proto.RegisterType((*GetAllRestaurantRequest)(nil), "restaurant_service.GetAllRestaurantRequest")
}

func init() { proto.RegisterFile("protos/restaurant.proto", fileDescriptor_2a748d3fbc2b9a53) }

var fileDescriptor_2a748d3fbc2b9a53 = []byte{
	// 570 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x5d, 0x6f, 0xd3, 0x30,
	0x14, 0xad, 0xd7, 0x2c, 0xed, 0x6e, 0xc7, 0x54, 0xac, 0x76, 0x0d, 0x79, 0x40, 0x21, 0x08, 0x11,
	0xbe, 0x4a, 0x15, 0x9e, 0x78, 0x41, 0x2a, 0x65, 0x9b, 0x26, 0x55, 0x3c, 0xb8, 0x03, 0x24, 0x5e,
	0xaa, 0x2c, 0xf1, 0x2a, 0x4b, 0x69, 0x5c, 0x62, 0x97, 0xbd, 0xf3, 0xca, 0x8f, 0xe1, 0x7f, 0xf0,
	0xab, 0x50, 0xdd, 0x34, 0xa1, 0xa9, 0x8b, 0xca, 0xb6, 0xa7, 0xd8, 0x57, 0xe7, 0xfa, 0x9c, 0x7b,
	0xee, 0x91, 0x02, 0x9d, 0x59, 0xca, 0x25, 0x17, 0xaf, 0x53, 0x2a, 0x64, 0x30, 0x4f, 0x83, 0x44,
	0x76, 0x55, 0x05, 0xe3, 0xa2, 0x32, 0x16, 0x34, 0xfd, 0xce, 0x42, 0xea, 0xfe, 0xde, 0x03, 0x20,
	0x79, 0x19, 0xb7, 0xc1, 0x4c, 0xa9, 0x18, 0xb3, 0xc8, 0x42, 0x0e, 0xf2, 0x0c, 0xb2, 0x9f, 0x52,
	0x71, 0x1e, 0x61, 0x0c, 0x46, 0x12, 0x4c, 0xa9, 0xb5, 0xe7, 0x20, 0xef, 0x80, 0xa8, 0x33, 0x3e,
	0x06, 0x33, 0x0d, 0x24, 0x4b, 0x26, 0x56, 0xd5, 0x41, 0x1e, 0x22, 0xd9, 0x0d, 0xdb, 0x50, 0x0f,
	0xe7, 0x4c, 0xb0, 0x84, 0x0a, 0xcb, 0x70, 0xaa, 0xde, 0x01, 0xc9, 0xef, 0xd8, 0x81, 0xc3, 0x90,
	0x0b, 0x39, 0xbe, 0xe2, 0xe9, 0x58, 0x5e, 0x73, 0x6b, 0x5f, 0x75, 0xc2, 0xa2, 0x76, 0xca, 0xd3,
	0x8b, 0x6b, 0x8e, 0x1f, 0xc1, 0x21, 0x9f, 0xd1, 0x84, 0x25, 0x93, 0xb1, 0x64, 0x53, 0x6a, 0x99,
	0x8a, 0xb1, 0x91, 0xd5, 0x2e, 0xd8, 0x94, 0x2e, 0x20, 0x61, 0xcc, 0x45, 0x0e, 0xa9, 0x2d, 0x21,
	0x59, 0x4d, 0x41, 0x06, 0x50, 0x8f, 0x79, 0x18, 0x48, 0xc6, 0x13, 0xab, 0xee, 0x20, 0xaf, 0xe1,
	0x3f, 0xed, 0x6e, 0x0e, 0xdf, 0x2d, 0x06, 0xef, 0x0e, 0x33, 0x38, 0xc9, 0x1b, 0xed, 0x1e, 0xd4,
	0x57, 0x55, 0xdc, 0x84, 0x6a, 0x1c, 0x48, 0x65, 0x0a, 0x22, 0x8b, 0xe3, 0xc2, 0x92, 0x98, 0x27,
	0x13, 0x65, 0x09, 0x22, 0xea, 0xec, 0xfe, 0x40, 0x60, 0x8e, 0x64, 0x20, 0xe7, 0x02, 0xbf, 0x05,
	0x23, 0xe4, 0x11, 0x55, 0x1d, 0x47, 0xfe, 0x13, 0x1d, 0xfb, 0x12, 0x99, 0x7d, 0x06, 0x3c, 0xa2,
	0x44, 0xb5, 0x60, 0x0b, 0x6a, 0x53, 0x2a, 0x44, 0x30, 0x59, 0xf9, 0xbd, 0xba, 0xba, 0x8f, 0x01,
	0x0a, 0x34, 0xae, 0x83, 0x71, 0xda, 0x3f, 0x1f, 0x36, 0x2b, 0xb8, 0x01, 0xb5, 0xd1, 0xa7, 0xc1,
	0xe0, 0x64, 0x34, 0x6a, 0x22, 0xf7, 0x33, 0xb4, 0xfa, 0x51, 0x54, 0x8c, 0x46, 0xe8, 0xb7, 0x39,
	0x15, 0x12, 0xbf, 0x03, 0x28, 0x44, 0x28, 0x5d, 0x0d, 0xff, 0xe1, 0xbf, 0x5d, 0x21, 0x7f, 0x75,
	0xb8, 0x97, 0xd0, 0x2e, 0xbd, 0x2b, 0x66, 0x3c, 0x11, 0x74, 0x5b, 0x66, 0x7c, 0x30, 0x85, 0x12,
	0xab, 0xa6, 0x68, 0xf8, 0xf6, 0x76, 0x0f, 0x48, 0x86, 0x74, 0x5f, 0x41, 0xeb, 0x8c, 0xca, 0x4d,
	0xed, 0x7a, 0x0a, 0xf7, 0x27, 0x82, 0x76, 0x09, 0x9f, 0x69, 0xba, 0xe5, 0xb0, 0x37, 0x12, 0xff,
	0x05, 0xda, 0x27, 0x11, 0x93, 0x77, 0xef, 0xfc, 0x10, 0x8e, 0xcb, 0x0f, 0x67, 0x63, 0xde, 0x44,
	0x66, 0x0f, 0x3a, 0x1f, 0x68, 0x4c, 0x25, 0xdd, 0xd9, 0xe6, 0x8f, 0x60, 0x6d, 0x76, 0xdc, 0x42,
	0xc1, 0x03, 0xe8, 0x9c, 0x51, 0xd9, 0x8f, 0xe3, 0x0d, 0x05, 0xfe, 0x2f, 0x03, 0xee, 0x17, 0xd5,
	0xd1, 0xb2, 0x1f, 0x5f, 0xc1, 0xbd, 0xb5, 0xe8, 0x61, 0x4f, 0xc7, 0xa2, 0x4b, 0xbd, 0xfd, 0x6c,
	0x07, 0xe4, 0x72, 0x14, 0xb7, 0xb2, 0xe0, 0x59, 0x8b, 0x93, 0x9e, 0x47, 0x97, 0x50, 0x3d, 0x8f,
	0x36, 0x9b, 0x6e, 0x05, 0x33, 0x38, 0x5a, 0x5f, 0x28, 0xd6, 0xb6, 0x6b, 0xd3, 0x64, 0x3f, 0xdf,
	0x05, 0x9a, 0x53, 0x71, 0x68, 0x96, 0x77, 0x87, 0x5f, 0xe8, 0x5e, 0xd8, 0x92, 0x09, 0xfb, 0xe5,
	0x6e, 0xe0, 0x9c, 0x30, 0x81, 0x66, 0x79, 0xb9, 0x7a, 0xc2, 0x2d, 0x11, 0xf8, 0x2f, 0x27, 0x7b,
	0xe8, 0x7d, 0xeb, 0xab, 0xe6, 0xb7, 0x76, 0x69, 0xaa, 0x3f, 0xde, 0x9b, 0x3f, 0x01, 0x00, 0x00,
	0xff, 0xff, 0x1a, 0x52, 0xf9, 0xa2, 0x0c, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestaurantServiceClient is the client API for RestaurantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestaurantServiceClient interface {
	AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error)
	GetRestaurant(ctx context.Context, in *GetRestaurantRequest, opts ...grpc.CallOption) (*GetRestaurantResponse, error)
	EditRestaurant(ctx context.Context, in *EditRestaurantRequest, opts ...grpc.CallOption) (*EditRestaurantResponse, error)
	DeleteRestaurant(ctx context.Context, in *DeleteRestaurantRequest, opts ...grpc.CallOption) (*DeleteRestaurantResponse, error)
	GetAllRestaurant(ctx context.Context, in *GetAllRestaurantRequest, opts ...grpc.CallOption) (RestaurantService_GetAllRestaurantClient, error)
}

type restaurantServiceClient struct {
	cc *grpc.ClientConn
}

func NewRestaurantServiceClient(cc *grpc.ClientConn) RestaurantServiceClient {
	return &restaurantServiceClient{cc}
}

func (c *restaurantServiceClient) AddRestaurant(ctx context.Context, in *AddRestaurantRequest, opts ...grpc.CallOption) (*AddRestaurantResponse, error) {
	out := new(AddRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/AddRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetRestaurant(ctx context.Context, in *GetRestaurantRequest, opts ...grpc.CallOption) (*GetRestaurantResponse, error) {
	out := new(GetRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/GetRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) EditRestaurant(ctx context.Context, in *EditRestaurantRequest, opts ...grpc.CallOption) (*EditRestaurantResponse, error) {
	out := new(EditRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/EditRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) DeleteRestaurant(ctx context.Context, in *DeleteRestaurantRequest, opts ...grpc.CallOption) (*DeleteRestaurantResponse, error) {
	out := new(DeleteRestaurantResponse)
	err := c.cc.Invoke(ctx, "/restaurant_service.RestaurantService/DeleteRestaurant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restaurantServiceClient) GetAllRestaurant(ctx context.Context, in *GetAllRestaurantRequest, opts ...grpc.CallOption) (RestaurantService_GetAllRestaurantClient, error) {
	stream, err := c.cc.NewStream(ctx, &_RestaurantService_serviceDesc.Streams[0], "/restaurant_service.RestaurantService/GetAllRestaurant", opts...)
	if err != nil {
		return nil, err
	}
	x := &restaurantServiceGetAllRestaurantClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type RestaurantService_GetAllRestaurantClient interface {
	Recv() (*GetRestaurantResponse, error)
	grpc.ClientStream
}

type restaurantServiceGetAllRestaurantClient struct {
	grpc.ClientStream
}

func (x *restaurantServiceGetAllRestaurantClient) Recv() (*GetRestaurantResponse, error) {
	m := new(GetRestaurantResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// RestaurantServiceServer is the server API for RestaurantService service.
type RestaurantServiceServer interface {
	AddRestaurant(context.Context, *AddRestaurantRequest) (*AddRestaurantResponse, error)
	GetRestaurant(context.Context, *GetRestaurantRequest) (*GetRestaurantResponse, error)
	EditRestaurant(context.Context, *EditRestaurantRequest) (*EditRestaurantResponse, error)
	DeleteRestaurant(context.Context, *DeleteRestaurantRequest) (*DeleteRestaurantResponse, error)
	GetAllRestaurant(*GetAllRestaurantRequest, RestaurantService_GetAllRestaurantServer) error
}

// UnimplementedRestaurantServiceServer can be embedded to have forward compatible implementations.
type UnimplementedRestaurantServiceServer struct {
}

func (*UnimplementedRestaurantServiceServer) AddRestaurant(ctx context.Context, req *AddRestaurantRequest) (*AddRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) GetRestaurant(ctx context.Context, req *GetRestaurantRequest) (*GetRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) EditRestaurant(ctx context.Context, req *EditRestaurantRequest) (*EditRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EditRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) DeleteRestaurant(ctx context.Context, req *DeleteRestaurantRequest) (*DeleteRestaurantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRestaurant not implemented")
}
func (*UnimplementedRestaurantServiceServer) GetAllRestaurant(req *GetAllRestaurantRequest, srv RestaurantService_GetAllRestaurantServer) error {
	return status.Errorf(codes.Unimplemented, "method GetAllRestaurant not implemented")
}

func RegisterRestaurantServiceServer(s *grpc.Server, srv RestaurantServiceServer) {
	s.RegisterService(&_RestaurantService_serviceDesc, srv)
}

func _RestaurantService_AddRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).AddRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/AddRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).AddRestaurant(ctx, req.(*AddRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).GetRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/GetRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).GetRestaurant(ctx, req.(*GetRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_EditRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EditRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).EditRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/EditRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).EditRestaurant(ctx, req.(*EditRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_DeleteRestaurant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRestaurantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestaurantServiceServer).DeleteRestaurant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restaurant_service.RestaurantService/DeleteRestaurant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestaurantServiceServer).DeleteRestaurant(ctx, req.(*DeleteRestaurantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RestaurantService_GetAllRestaurant_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetAllRestaurantRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RestaurantServiceServer).GetAllRestaurant(m, &restaurantServiceGetAllRestaurantServer{stream})
}

type RestaurantService_GetAllRestaurantServer interface {
	Send(*GetRestaurantResponse) error
	grpc.ServerStream
}

type restaurantServiceGetAllRestaurantServer struct {
	grpc.ServerStream
}

func (x *restaurantServiceGetAllRestaurantServer) Send(m *GetRestaurantResponse) error {
	return x.ServerStream.SendMsg(m)
}

var _RestaurantService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restaurant_service.RestaurantService",
	HandlerType: (*RestaurantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddRestaurant",
			Handler:    _RestaurantService_AddRestaurant_Handler,
		},
		{
			MethodName: "GetRestaurant",
			Handler:    _RestaurantService_GetRestaurant_Handler,
		},
		{
			MethodName: "EditRestaurant",
			Handler:    _RestaurantService_EditRestaurant_Handler,
		},
		{
			MethodName: "DeleteRestaurant",
			Handler:    _RestaurantService_DeleteRestaurant_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetAllRestaurant",
			Handler:       _RestaurantService_GetAllRestaurant_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "protos/restaurant.proto",
}
